$(document).ready(function(){
	$(".clickpop").click(function(){
		$(".clickpop").fadeOut("fast");
		$(".nav").fadeIn("slow");
	});

	$(".closemoi").click(function(){
		$(".nav").fadeOut("fast");
		$(".clickpop").fadeIn("slow");
	});
	/*Sidebar*/
	$('.register').click(function(){
		$('.logisfil').fadeIn('fast');
	});
	$('.login').click(function(){
		$('.logisfil').fadeIn('fast');
	});
	$('.closelogisfil').click(function(){
		$('.logisfil').fadeOut('fast');
	});
});